[tool.poetry]
name = "incoker-inv"
version = "0.1.0"
description = ""
authors = ["rayan967 <36110753+rayan967@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "incoker_inv"}]

[tool.poetry.dependencies]
python = "^3.11"
scikit-learn = "1.3.0"
pytest = "^7.3.1"
pydoe = "^0.3.8"
tabulate = "^0.9.0"
jax = "^0.4.13"
jaxlib = "^0.4.13"
scikit-optimize = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
