property_name: thermal_conductivity

simulation_options:
  particle_quantity: 200
  dim: 32
  max_vertices: 25000

parameterranges:
  VolumeFractionZirconia: [0.15, 0.85]
  ChordLengthRatio: [0.3, 4.0]

adaptive_phase_parameters:
  totalbudget: 1.0E20 # Total budget to spend, to be implemented (TBI)
  incrementalbudget: 1.0E5 # Incremental budget, TBI
  TOLFEM: 0.0   # Reevaluation tolerance, TBI
  TOLAcqui: 1.0   # Acquisition tolerance
  TOLrelchange: 0   # Tolerance for relative change of global error estimation
  TOL: 0    # Needs to be set based on property, but set to 0 for full evaluation

multiple_generation_options:
  usage: true
  num_generations: 5

execpath: './adapt'
validation_data_path: "/data/pirkelma/adaptive_gp_InCoKer/thermal_conductivity/20231215/validation_data/mean/test_data_32_thermal_conductivity"
compute: true     # If initial points are available or restarting a failed run, set compute = False
output_freq: 5
max_samples: 150